apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-test
  template:
    metadata:
      labels:
        app: cicd-test
    spec:
      containers:
        - name: cicd-test
          image: tayadepss/cicd-test-pipeline:1.0.0-53
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
